### ISSUE TITLE
Deletes service files in case of etcd connection problems

### ISSUE THREAD

**Issue by balboah** [coreos/fleet#1145]
It seems fleet likes to delete already running systemd services if it loses contact with etcd.
I'm running a http proxy on all instances except a few "core" ones which has the real etcd, unfortunately this proxy lost its connection to upstream giving HTTP 503 instead.

This caused services that was running happily to be removed by fleet, I would not expect this to be the default behavior. Instead I expect service files to be left alone unless a task says explicitly to destroy them.

**Comment by robszumski** [comment]
What version of CoreOS is this on?

**Comment by bcwaldon** [comment]
@balboah This is by design. fleet's goal is more on the consistency end of the spectrum rather than availability, meaning that if fleet can't tell what it should be doing, it needs to revert to the safest state possible. fleet depends on etcd to tell what it should be doing, so if it can't communicate with etcd, it must revert to doing nothing. For example, in the event of a network split, the scheduler will move work to healthy nodes, but it has no way to communicate to the unhealthy nodes that they no longer are responsible for their jobs.

**Comment by balboah** [comment]
Ok. Thanks.
You could argue that actively removing already scheduled services is not
the same as "doing nothing" but I understand the design decision. I'll try
to make the etcd part work better instead.

måndag 9 mars 2015 skrev Brian Waldon <notifications@github.com>:

**Comment by bcwaldon** [comment]
@balboah "doing nothing" meaning an unhealthy fleet agent is not allowed to execute any more work. We have discussed the concept of a unit SLA before, but I can't seem to find where that was documented. Basically, we want to be able to define a policy that should be applied to a given unit when its host "goes away": basically whether to reschedule after N seconds or to never move the job. If you want to get a functional specification together for this behavior, I would be more than happy to work with you to get it implemented.
