### ISSUE TITLE
v 0.10.0 - Defaulting to fleet API versus etcd is a complete reversal from current standards

### ISSUE THREAD

**Issue by popsikle** [coreos/fleet#1193]
So I updated fleetctl on my deployment nodes to find out that without using the etcd driver flag all of my processes stopped working.  Had a conversation on IRC about it, and it seems that this change was intentional because the security risks of having an exposed etcd service.  I take some issue with this, not because I don't see the security risks but because its a complete 180 from the docs and current standards.

Generally speaking, most of the docs (https://coreos.com/docs/launching-containers/launching/launching-containers-fleet/#run-a-simple-sidekick for example) imply that writing directly to etcd as a general k/v store AS WELL AS your fleetd endpoint is the expected use case.  the fact there there have been a bunch of supporting services (confd, cryptd, etc) that are used pretty heavily within the community also backs the idea that etcd as k/v is the expected use case.

Its a little too late IMHO to back pedal on the idea that you should not be using etcd for k/v as well as fleet.

Maybe Im crazy?

**Comment by bcwaldon** [comment]
We've successfully made the transition, so I don't think we went too far towards writing directly to etcd. So on that point, I don't think it was the wrong decision.

As far as why - that's due to how frustrating it has been to manage schemas and migrations through etcd rather than an API. It sucks giving your users access to your datastore. Kubernetes, for example, has made the same transition leading up to their 1.0.
