### ISSUE TITLE
fleetctl stop is slow with large number of units

### ISSUE THREAD

**Issue by iamruinous** [coreos/fleet#1343]
Similar to #1340, stop and unload are also incredibly slow when a large number of unit files exist (~2500).

Submitting a pull request in a bit.

**Comment by wuqixuan** [comment]
I totally agree that no need get all unit information.

**Comment by ivankennethwang** [comment]
+1

**Comment by dongsupark** [comment]
As described in https://github.com/coreos/fleet/pull/1344#issuecomment-263322855, using `Unit()` instead of `Units()` will make the performance rather worse. So I'll close this issue for now.
If anyone has a better idea to improve the performance in a generic manner, please create another PR to do so. Thanks.
