### ISSUE TITLE
where is oncalendar=now

### ISSUE THREAD

**Issue by rbucker** [coreos/fleet#1385]
My timer file:
```
[Unit]
Description=HelloWorldOnce zquery report

[Timer]
OnCalendar=now
Persistent=true

[Install]
WantedBy=local.target
```

the output:
```
Nov 01 18:31:57 ip-172-31-28-78.us-west-2.compute.internal systemd[1]: [/run/fleet/units/HelloWorldOnce.timer:5] Failed to parse calendar specification, ignoring: now
Nov 01 18:31:57 ip-172-31-28-78.us-west-2.compute.internal systemd[1]: HelloWorldOnce.timer: Timer unit lacks value setting. Refusing.
```

I have seen an example of someone using the ```daily``` and I have confirmed that it works. ```now``` is documented in the systemd docs.

**Comment by rbucker** [comment]
I also tried +0

**Comment by rbucker** [comment]
I also tried 1min

**Comment by rbucker** [comment]
OnCalendar is not a monotonic timer.

**Comment by sukrit007** [comment]
Just ran into this. Shouldn't this be supported as per systemd specs ?

**Comment by kayrus** [comment]
@rbucker systemd should not handle `now`, `today`, `tomorrow`, etc. [timestamps](https://www.freedesktop.org/software/systemd/man/systemd.time.html#Parsing%20Timestamps) for the periodic timers (otherwise it will just hang, I suppose). In your case you have to use [calendar events](https://www.freedesktop.org/software/systemd/man/systemd.time.html#Calendar%20Events).
