### ISSUE TITLE
tests: set up functional tests on CI

### ISSUE THREAD

**Issue by jonboulle** [coreos/fleet#1403]
The functional test suite should be integrated with a CI system so we can run against master and every PR that is submitted to the project.

**Comment by kayrus** [comment]
We could try to implement these tests here: https://github.com/coreos/mantle

@jonboulle what do you think? Does it suit?

**Comment by jonboulle** [comment]
@kayrus sure. There's an extremely simple fleet test [baked in there](https://github.com/coreos/mantle/blob/master/kola/tests/fleet/fleet.go) but it would be great if we could get the whole functional suite integrated. Can you work with @pbx0 perhaps?

**Comment by pbx0** [comment]
If you both are reasonably happy with the kola test interface, I am happy to help get more tests added.

One advantage of using kola is that, we will run the fleet tests automatically against each OS release. 

One disadvantage is that, if you use kola for testing your PRs, you would have to build an OS image with fleet baked in to run the existing tests. It'd probably be better to build a kola subcommand that takes a git commit hash as an argument that you then run in your own CI environment (Jenkins or otherwise). The subcommand would build fleet off the commit and copy that binary onto the machines before running the tests.

I wish kola had better ways to support individual project workflows (rather then the OS release process only) so that it would be more attractive for projects like fleet to build all their tests in kola. But, again, I'm happy to help you work through this and maybe make some kola improvements along the way.

**Comment by jonboulle** [comment]
mantle would be ideal. In the interim, as @mirkoboehm pointed out, we could simply hook up a Jenkins instance to spinning up a VM and running the existing functional test suite in it, and then ensuring the results are exposed somehow (e.g. uploading output to storage somewhere) - this is what kubernetes does for example: https://github.com/kubernetes/kubernetes/pull/20553#issuecomment-179439568

**Comment by kayrus** [comment]
I'm trying to create script which will run test on CI in this ticket: https://github.com/coreos/fleet/pull/1430

**Comment by mirkoboehm** [comment]
To get the functional tests running on CI, we need to have "bare-metal"-like control over the test environment. We decided to run the tests in a VM that is created automatically and reproducibly with Vagrant. The creation of the test environment and running the tests in it will be done by a single script. This can then be hooked into a CI that allows the creation of VMs. It also serves as a reference environment that can be run on a developer machine to verify that that functional tests still succeed with work-in-progress. The priority is on CI. 
Three systems are involved: 

* The _parent_: This is the system that creates the test VM. In CI, this is the build slave. It needs to have Vagrant and to support the sharing of folder with the test VM once it is running (standard Vagrant behaviour, but requires NFS or a similar mechanism). The parent will have a clone of the fleet repository, from which the run-tests-in-VM.sh script will be called. The repo will be mounted into the test VM under /vagrant (default Vagrant behaviour). 

* The _test host_: This is the CoreOS machine that is used to build fleet and run the tests. It is considered ephemeral. The tests are executed on this machine. The build environment is installed on the test host. The parent setup is not modified when the build environment for the test host is set up.

* The _fleet instance_ nspawn containers: These are created and destroyed by the functional test suite to perform the actual tests.

The whole setup is designed as an entry point for general CI systems (e.g., Jenkins). All it requires is a build slave that is able to create VMs with Vagrant and share folders with them.

**Comment by kayrus** [comment]
closed via #1462
