### ISSUE TITLE
Force services to be run by a specific user

### ISSUE THREAD

**Issue by hmalphettes** [coreos/fleet#1479]
Hi!

I am deploying fleet in an environment that relies on separating what root can do from what the administrator of a specific application can do.
I would like to be able to grant `fleetctl {submit,start}` access to the administrator rather than root alone.
`fleetctl {submit,start}` trivially provides root access as services can be executed on behalf of any user including root.

I was hoping to take advantage of `systemd --user` (https://github.com/coreos/fleet/pull/1393) but that wont be supported in systemd until further notice.

Here would be an attempt at reproducing the type of limitation enforced by `systemd --user`:
Every service executed by fleet must contain the following directives:
```
[Service]
User=wwwadmin
Group=wwwadmin
PermissionsStartOnly=false
```

Is this a reasonable approach?
Is there a specific location for a conf file to override/insert those directives on the file system?
Is this something that must be implemented in fleetd: parse and reject submitted services according to a template of some kind? If that is the case I am happy to attempt to contribute it.

Many thanks for your help!

**Comment by kayrus** [comment]
One of the possible solutions is to implement [drop-in](https://github.com/coreos/docs/blob/master/os/using-systemd-drop-in-units.md) support. The question is where to store these drop-ins and how to manage them? As soon as we merge this https://github.com/coreos/fleet/pull/1506 PR, we can store this data inside etcd registry with world wide read-only permissions.

Drop-in example: `10-user-restriction.conf`

```ini
[Service]
User=wwwadmin
Group=wwwadmin
PermissionsStartOnly=false

[X-Fleet]
Service=myunitfile.service
```

or

```ini
[Service]
User=wwwadmin
Group=wwwadmin
PermissionsStartOnly=false

[X-Fleet]
Service=www*.service
MachineID=6ed03b01bd28ea40a07ff8c35e76bdc6
MachineMetadata=foo=bar
MachineOf=www*.service
```

We will have to implement `list-drop-ins`, `submit-drop-in`, `destroy-drop-in`, etc.

Also it will require ACL implementation on the fleetd side, because unix/tcp sockets can not determine who has connected.

Second solution (mostly workaround):

Create these systemd unit files:

`/etc/systemd/system/monitor-fleet.path`:

```ini
[Unit]
Description=Watch for units inside /run/fleet/units directory
After=fleet.service
BindsTo=fleet.service

[Path]
PathChanged=/run/fleet/units

[Install]
RequiredBy=fleet.service
```

`/etc/systemd/system/monitor-fleet.service`:

```ini
[Unit]
ConditionDirectoryNotEmpty=/run/fleet/units
After=fleet.service

[Service]
Type=oneshot
ExecStart=/opt/bin/fleet-drop-ins.sh
```

`/opt/bin/fleet-drop-ins.sh`:

```sh
#!/bin/bash

DROPIN="[Service]\nUser=core"

SYSTEMD_RUN_DIR=/run/systemd/system
FLEET_RUN_DIR=/run/fleet/units

for unit in $(ls ${FLEET_RUN_DIR}/*.service); do
  BASENAME=$(basename ${unit})
  mkdir -p ${SYSTEMD_RUN_DIR}/${BASENAME}.d
  echo -e "$DROPIN" > ${SYSTEMD_RUN_DIR}/${BASENAME}.d/99-fleet.conf
done
```

then run `sudo systemctl daemon-reload && systemctl enable monitor-fleet.path`.

Now once you've added unit file using fleet it will print:

```sh
fleetctl journal hello.service
-- Logs begin at Wed 2016-03-30 11:11:01 UTC, end at Thu 2016-03-31 19:13:38 UTC. --
Mar 31 19:13:30 coreos1 systemd[1]: Started hello.service.
Mar 31 19:13:38 coreos1 bash[12942]: Hello, World, I am 500!
```

**Comment by hmalphettes** [comment]
@kayrus Many thanks for this! Much appreciated.
Let me know if we should mark this question as answered : close the issue?

**Comment by kayrus** [comment]
@hmalphettes if you wish to implement first solution yourself - keep this issue closed.

**Comment by tixxdz** [comment]
@kayrus 

> Also it will require ACL implementation on the fleetd side, because unix/tcp sockets can not determine who has connected.

To be correct, unix sockets can determine that see SCM_CREDENTIALS etc... but honestly I'm even sure if this enters totally into fleetd scope...

**Comment by hmalphettes** [comment]
@kayrus noted with thanks!
@kayrus The solution you suggested is better than what I had in mind.
I was planning to configure fleet on each machine so the workaround you provided is exactly what I need.
