### ISSUE TITLE
Official rkt images

### ISSUE THREAD

**Issue by monder** [coreos/fleet#1665]
Are there any official `aci` images for the release? Could we have something similar to https://github.com/coreos/etcd/releases please :)

**Comment by jonboulle** [comment]
@dongsupark any chance you could take a look at this?

**Comment by dongsupark** [comment]
@jonboulle Sure, I'll try to do it this week.

**Comment by dongsupark** [comment]
@jonboulle Using the script written via https://github.com/coreos/fleet/pull/1682, I created 2 ACI images for [v0.12.0](https://github.com/coreos/fleet/releases/download/untagged-363e0bcd48d932709996/fleetd-v0.12.0-amd64.aci) and [v0.13.0](https://github.com/coreos/fleet/releases/download/untagged-17375173c52162328e64/fleetd-v0.13.0-amd64.aci).

Next step would be to release them on https://github.com/coreos/fleet/releases. Currently I cannot do that, because I don't have a gpg private key for "CoreOS ACI Builder". How should I proceed?

Another question: How can I allow the ACI image to be discovered by rkt run, like "rkt run ...  coreos.com/fleet:v0.13.0"?

**Comment by dongsupark** [comment]
ACI images are already provided for v0.11.8, v0.12.0, and v0.13.0. I'm going to provided ACI also for the future release v1.0.
So I suppose this issue can be closed.
