### ISSUE TITLE
container: create a fleet docker container

### ISSUE THREAD

**Issue by philips** [coreos/fleet#1705]
We need to generate a docker image for fleet that people can use after bind-mounting in the systemd socket.

**Comment by philips** [comment]
@dongsupark if I give you access to quay.io/coreos/fleet do you think you could generate and push containers of the last few releases?

**Comment by dongsupark** [comment]
@philips Sure, I will do.
Please give the permission to my quay account [dongsupark](https://quay.io/user/dongsupark). Thanks.

**Comment by dongsupark** [comment]
"[quay.io/coreos/fleet](https://quay.io/coreos/fleet)" was created, and it's now open for everyone.
It works also fine. I tested by running `"rkt run ... quay.io/coreos/fleet:v0.13.0"`

Next step would be to create documents and examples, so that users can easily run fleet via rkt. I have been testing it with coreos-baremetal and ignition. (https://github.com/endocode/coreos-baremetal/tree/dongsu/fleet-examples)

I'll track remaining works on https://github.com/coreos/bugs/issues/1669.
