### ISSUE TITLE
Use systemd-journal-gatewayd for "fleetctl journal"

### ISSUE THREAD

**Issue by jonboulle** [coreos/fleet#355]
Instead of SSHing and running `journalctl` locally, why not use the systemd service [built for this kind of purpose](http://www.freedesktop.org/software/systemd/man/systemd-journal-gatewayd.service.html)?

The only downside I'd see is the additional port requirement. But arguably even just tunneling this over SSH would make more sense than what we're doing today.

Thoughts?

**Comment by ChimeraCoder** [comment]
@jonboulle Correct me if I'm wrong, but `systemd-journal-gatewayd` doesn't provide access to [trusted journal fields](http://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#Trusted%20Journal%20Fields) - in other words, anything prefixed with one or more underscores, such as `_PID`, `_SYSTEMD_UNIT`, etc. So if you want access to any of those, you'll still have to leave journalctl as a fallback option for querying based on those fields.

(I would love to be corrected on this, because I've hit this exact same stumbling point in [my Go client library for journalctl.systemd-journal-gatewayd](https://github.com/ChimeraCoder/journalctl-go), which is how I found this issue!)

**Comment by bcwaldon** [comment]
Superseded by #1123
