### ISSUE TITLE
Add functional test coverage for Agent's loss of etcd connectivity

### ISSUE THREAD

**Issue by bcwaldon** [coreos/fleet#715]
Related https://github.com/coreos/fleet/issues/708

We need to add a functional test that ensures that the fleet agent behaves correctly when it loses access to the etcd cluster.

**Comment by wuqixuan** [comment]
+1

**Comment by themicster** [comment]
+1, So it turns out in order to simulate etcd being down as in a case where the etcd machine is dead you have to ignore packets to or from the IP that etcd should be running on. In normal behavior of an up machine you'll receive an ICMP that tells you that the connection is refused from the machine because it is not listening on that port. This results in the client instantly trying the next etcd server, which is great and there is no problem.
But in the case of the machine being dead there is no ICMP packet sent back and the client will wait for normally a long timeout period before trying the next etcd server. Which is where I figured the HeaderTimeoutPerRequest would come in handy. But I agree a test should be created to simulate this condition of non-existent machine in the etcd list.
So, in order to do that properly I have found that you cannot simply stop etcd on a server. You have to drop the packets to/from that server to simulate the whole machine being offline. Or you can put an invalid IP address in the list of etcd machines, but I would think this would be much more difficult, but maybe not. Also keep in mind there is a new pinning system that will pin good servers, so you will need to make sure that it is not just skipping the server altogether. I believe it retries all the servers every 10 seconds or so and then decides which one to pin.

I'm not sure how your test environment is setup, but in my case I have a cumulus switch I can put an iptables rule in to prevent traffic to/from a server. I think you could also simulate this without loosing complete connectivity to the machine by just dropping all ICMP, or find the specific icmp type that gets sent for "connection refused" and block that. Be sure you understand the actual packet flow here because it's been a while since I've read TCP/IP Illustrated, I could be missing something. But I hope this helps.

**Comment by antrik** [comment]
So I think this needs some clarification on what exactly we want to test here.

First of all, AIUI this is about total loss of connectivity to the entire etcd cluster -- failover handling is an entirely different issue, right? As the functional test currently all work with a single etcd instance, this should be more or less straightforward I guess...

Next question is about what exactly "loss of connectivity" means. Should we test the clear-cut case when we get an immediate error response, e.g. when the etcd process went down? Or the case where we don't get replies (but eventually a timeout I guess) when the server process or the network just hangs? Or both?

Also, what exactly do we want to test when connectivity is lost? Just that the state of existing units doesn't change on the disconnected node, or also how the rest of the cluster behaves? And if it's the latter, what do we actually expect there?... What about reconciliation once connectivity is re-established?

**Comment by themicster** [comment]
antrik, it's hard to determine the original intent of 708 and 715, but obviously both cases need to be tested and handle correctly. The two cases are total loss of connectivity to the entire etcd cluster and loss of connectivity to one or two etcd instances. So Let's look at them separately. First lets define what we mean by these and maybe what is required to determine these states. You could split total loss into two different states, but I think for now the treatment/response of total loss or quorum lost is probably going to be the same.

Total Loss of connectivity: fleet is unable to get a response from any etcd server, or it get's a response from an etcd server but it is not writable and quorum has been lost. 

Loss of an etcd instance: fleet is unable to get a response from one or more etcd server(s) but etcd is still writable and quorum has not been lost (this is evidenced by etcd still being writable).

So, if you define these two states this way, you don't need to worry about ICMP returning connection refused or not, because you'll try the other servers anyways. Currently reconciling every 10 seconds would be too short for trying all the servers, especially if the timeout for a response is higher than that or even half of that because there wouldn't be enough time to try each node before reconcile kicks in and starts restarting services.

There is also the tricky matter of pinning and proxies. If you contact an etcd proxy and it fails to respond, then you'll have to try the other proxies and the primary etcd nodes, or skip right to trying the primaries. Because when you try a proxy, each one might be pinned on the same primary node which could be down, so not getting a response from a proxy doesn't tell you which primary etcd node the proxy tried. But I'd have to look at the code to see what response would be given in this case where you can contact the proxy but the proxy fails to contact the etcd server. Does the proxy retry the other etcd nodes here? Does it have enough time if the etcd server does not respond right away with a connection refused? Most likely it does not have a long enough timeout in this case.

There are a lot of timeouts involved here at many different levels, and if they are not all thought about correctly and intentionally set with all the other timeouts in mind, something is not going to work correctly in some case. When I say "timeout" I'm speaking generally here, but knowing there are timeouts for each socket function (connect, send, receive, close) and all of them must be considered along with the timeouts of the system it is calling and the timeouts of the system calling it. For example, in the case of fleet->proxy->etcd.

This is not rocket science, it's just basic math with a deep understanding of sockets and protocols. This only becomes a hard problem if you forget to think about one of the timing factors. You could make this a hard problem by trying to think of even more timing factors than are needed and what to do in really blue moon cases such as partial responses or response received but close socket times out. This isn't necessary to get a pretty good system in place though. Let's cover the easily knowable cases first. And if we get all the timeouts right, it can gracefully handle anything else that may occur in a blue moon case as well. We just might want to define a better response to blue moon cases later.

Sorry, I may have gone off on a bit of a tangent there. Let's get back to the questions at hand, which is what to test and what the expected outcome should be.

If we can agree on these two states and their definition we can start writing some test cases to cover these states. As for the outcomes, I would like to see the following:

Total loss of connectivity: Nothing changes, reconcile does not stop or start any units until connectivity has been restored and we can see that some services have been rescheduled on other servers or not.

Loss of an instance: Everything should run as normal, no change. Units continue to run, reconcile is able to handle the loss of one instance or n instances as long as there is still a quorum.

Currently as implemented testing for both of these outcomes would fail. Let's get some more people's input on this and nail down the definitions and states as well as what the outcomes should be and then we can write some test cases that will cover some different ways to get into these states.

**Comment by themicster** [comment]
So after reviewing #708 again, I think it can be made even simpler for a phase one set of tests. Some tests need to be created that can simulate flapping etcd in two ways, etcd service on a machine is starting and stopping and the machine etcd is running on is loosing connectivity. But because of the pinning behavior, the test may fail sometimes and succeed other times with no change to infrastructure.

**Comment by jonboulle** [comment]
> First of all, AIUI this is about total loss of connectivity to the entire etcd cluster -- failover handling is an entirely different issue, right? 

Yes

> Next question is about what exactly "loss of connectivity" means. Should we test the clear-cut case when we get an immediate error response, e.g. when the etcd process went down? 

Yes

> Or the case where we don't get replies (but eventually a timeout I guess) when the server process or the network just hangs? 

This would be nice to have but isn't an immediate requirement. Let's start with loss and go from there.

> Also, what exactly do we want to test when connectivity is lost? Just that the state of existing units doesn't change on the disconnected node, or also how the rest of the cluster behaves? 

Only the disconnected node.
