### ISSUE TITLE
Add "fleetctl restart"

### ISSUE THREAD

**Issue by ndarilek** [coreos/fleet#975]
Occasionally I rebuild a base Docker image and want to restart the unit, or occasionally a container gets stuck and requires a restart.

Under plain systemd I can just "systemctl restart whatever", but I routinely try that with fleetctl and fail. Sure I can stop then start, or just start if the unit is already stopped, but it's an area where fleetctl isn't symmetric with the tool it claims to emulate which throws me regularly. :)

Thanks.

**Comment by antrik** [comment]
So it turns out that none of the existing PRs trying to address this functionality can be merged, as the approaches they are using do not really fit in with fleet's way of doing things. (See discussion in https://github.com/coreos/fleet/issues/1238 for details.)

The plan now is ultimately to have a `restart` command that requests a specific desired state for the unit: it needs to have been last (re-)started after a specific timestamp. (By default, the moment when the `fleetctl restart` command was issued.) The agent is then responsible for restarting the unit during reconciliation if it doesn't fulfil this condition yet.

However, it seems that some (many?) users don't need such a sophisticated implementation, and basically just want a wrapper for `systemctl restart` -- in fact, that's more or less what the first PR ( https://github.com/coreos/fleet/pull/961 ) tried to do. We don't see a real need for implementing anything special for this use case though, as using the existing `fleetctl ssh` command with the the desired unit as the target and `systemctl restart <unit>` as the action should indeed produce the same effect.

Thus the "proper" implementation described before is not considered high priority; and explicitly mentioning the latter approach in the fleet documentation should be good enough for now.
